platform:
  - x64

cache:
  - node_modules
  - 'app\node_modules'
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'

# Code signing environment variables are declared in the project settings on AppVeyor.

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 5 x64
  - git reset --hard HEAD
  - npm install npm -g
  - npm prune
  - npm install

build_script:
  - node --version
  - npm --version
  - npm test
  - npm run dist

test: off
